/* Generated By:JJTree: Do not edit this line. Anonymous.java */
package org.codehaus.aspectwerkz.definition.expression.ast;

public class Anonymous extends SimpleNode
{
    public String name;

    public Anonymous(int id)
    {
        super(id);
    }

    public Anonymous(ExpressionParser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public String toString()
    {
        return name;
    }
}
