/* Generated By:JJTree: Do not edit this line. ExpressionScript.java */

package org.codehaus.aspectwerkz.definition.expression.ast;

public class ExpressionScript extends SimpleNode {
    public ExpressionScript(int id) {
        super(id);
    }

    public ExpressionScript(ExpressionParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
