/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionParserConstants.java */
package org.codehaus.aspectwerkz.definition.expression.ast;

public interface ExpressionParserConstants {

  int EOF = 0;
  int AND = 10;
  int OR = 11;
  int NOT = 12;
  int IDENTIFIER = 13;
  int LETTER = 14;
  int DIGIT = 15;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"(\"",
    "\")\"",
    "\"true\"",
    "\"false\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
