/* Generated By:JJTree: Do not edit this line. D:/aw/cvs_aw/aspectwerkz2/src/main/org/codehaus/aspectwerkz/definition/expression/ast\ExpressionParserTreeConstants.java */

package org.codehaus.aspectwerkz.definition.expression.ast;

public interface ExpressionParserTreeConstants
{
  public int JJTEXPRESSIONSCRIPT = 0;
  public int JJTVOID = 1;
  public int JJTORNODE = 2;
  public int JJTANDNODE = 3;
  public int JJTNOTNODE = 4;
  public int JJTIDENTIFIER = 5;
  public int JJTBOOLEANLITERAL = 6;
  public int JJTTRUENODE = 7;
  public int JJTFALSENODE = 8;


  public String[] jjtNodeName = {
    "ExpressionScript",
    "void",
    "OrNode",
    "AndNode",
    "NotNode",
    "Identifier",
    "BooleanLiteral",
    "TrueNode",
    "FalseNode",
  };
}
