/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionParserConstants.java */
package org.codehaus.aspectwerkz.definition.expression.ast;

public interface ExpressionParserConstants {

    int EOF = 0;
    int AND = 10;
    int OR = 11;
    int NOT = 12;
    int IN = 13;
    int IDENTIFIER = 14;
    int LETTER = 15;
    int DIGIT = 16;

    int DEFAULT = 0;

    String[] tokenImage = {
        "<EOF>",
        "\"(\"",
        "\")\"",
        "\"true\"",
        "\"false\"",
        "\" \"",
        "\"\\t\"",
        "\"\\n\"",
        "\"\\r\"",
        "\"\\f\"",
        "<AND>",
        "<OR>",
        "<NOT>",
        "<IN>",
        "<IDENTIFIER>",
        "<LETTER>",
        "<DIGIT>",
    };

}
