/* Generated By:JJTree: Do not edit this line. FalseNode.java */

package org.codehaus.aspectwerkz.definition.expression.ast;

public class FalseNode extends SimpleNode {
  public FalseNode(int id) {
    super(id);
  }

  public FalseNode(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
