/* Generated By:JJTree: Do not edit this line. NotInNode.java */

package org.codehaus.aspectwerkz.definition.expression.ast;

public class NotInNode extends SimpleNode {
    public NotInNode(int id) {
        super(id);
    }

    public NotInNode(ExpressionParser p, int id) {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
