/* Generated By:JJTree: Do not edit this line. TrueNode.java */
package org.codehaus.aspectwerkz.definition.expression.ast;

public class TrueNode extends SimpleNode
{
    public TrueNode(int id)
    {
        super(id);
    }

    public TrueNode(ExpressionParser p, int id)
    {
        super(p, id);
    }

    /** Accept the visitor. **/
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
