/* Generated By:JJTree: Do not edit this line. ASTGet.java */
package org.codehaus.aspectwerkz.expression.ast;

public class ASTGet extends SimpleNode
{
    public ASTGet(int id)
    {
        super(id);
    }

    public ASTGet(ExpressionParser p, int id)
    {
        super(p, id);
    }

    public Object jjtAccept(ExpressionParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }

    public void setType(String fieldType)
    {
    }

    public void setName(String fieldName)
    {
    }
}
