/* Generated By:JJTree: Do not edit this line. ASTPointcutReference.java */
package org.codehaus.aspectwerkz.expression.ast;

public class ASTPointcutReference extends SimpleNode {
    private String m_name;

    public ASTPointcutReference(int id) {
        super(id);
    }

    public ASTPointcutReference(ExpressionParser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void setName(String name) {
        m_name = name;
    }

    public String getName() {
        return m_name;
    }
}