/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionParserConstants.java */
/**************************************************************************************
 * Copyright (c) Jonas Bonér, Alexandre Vasseur. All rights reserved.                 *
 * http://aspectwerkz.codehaus.org                                                    *
 * ---------------------------------------------------------------------------------- *
 * The software in this package is published under the terms of the LGPL license      *
 * a copy of which has been included with this distribution in the license.txt file.  *
 **************************************************************************************/
package org.codehaus.aspectwerkz.expression.ast;

public interface ExpressionParserConstants {

  int EOF = 0;
  int COMMA = 3;
  int DOT = 4;
  int WILDCARD = 5;
  int ARRAY = 6;
  int EAGER_WILDCARD = 7;
  int AND = 8;
  int OR = 9;
  int NOT = 10;
  int EXECUTION = 11;
  int CALL = 12;
  int SET = 13;
  int GET = 14;
  int HANDLER = 15;
  int WITHIN = 16;
  int WITHIN_CODE = 17;
  int STATIC_INITIALIZATION = 18;
  int CFLOW = 19;
  int CFLOW_BELOW = 20;
  int ARGS = 21;
  int TARGET = 22;
  int THIS = 23;
  int IF = 24;
  int HAS_METHOD = 25;
  int HAS_FIELD = 26;
  int POINTCUT_REFERENCE_WITH_ARGS = 27;
  int POINTCUT_REFERENCE = 28;
  int CLASS_PRIVATE = 29;
  int CLASS_PROTECTED = 30;
  int CLASS_PUBLIC = 31;
  int CLASS_STATIC = 32;
  int CLASS_ABSTRACT = 33;
  int CLASS_FINAL = 34;
  int CLASS_NOT = 35;
  int CLASS_ATTRIBUTE = 36;
  int CLASS_PATTERN = 37;
  int CLASS_IDENTIFIER = 38;
  int CLASS_JAVA_NAME_LETTER = 39;
  int CLASS_POINTCUT_END = 40;
  int METHOD_PUBLIC = 41;
  int METHOD_PROTECTED = 42;
  int METHOD_PRIVATE = 43;
  int METHOD_STATIC = 44;
  int METHOD_ABSTRACT = 45;
  int METHOD_FINAL = 46;
  int METHOD_NATIVE = 47;
  int METHOD_SYNCHRONIZED = 48;
  int METHOD_NOT = 49;
  int METHOD_ANNOTATION = 50;
  int METHOD_IDENTIFIER = 51;
  int METHOD_CLASS_PATTERN = 52;
  int METHOD_ARRAY_CLASS_PATTERN = 53;
  int PARAMETER_START = 54;
  int PARAMETER_END = 55;
  int METHOD_JAVA_NAME_LETTER = 56;
  int FIELD_PRIVATE = 57;
  int FIELD_PROTECTED = 58;
  int FIELD_PUBLIC = 59;
  int FIELD_STATIC = 60;
  int FIELD_ABSTRACT = 61;
  int FIELD_FINAL = 62;
  int FIELD_TRANSIENT = 63;
  int FIELD_NOT = 64;
  int FIELD_ANNOTATION = 65;
  int FIELD_IDENTIFIER = 66;
  int FIELD_CLASS_PATTERN = 67;
  int FIELD_ARRAY_CLASS_PATTERN = 68;
  int FIELD_JAVA_NAME_LETTER = 69;
  int FIELD_POINTCUT_END = 70;
  int PARAMETER_IDENTIFIER = 71;
  int PARAMETER_CLASS_PATTERN = 72;
  int PARAMETER_ARRAY_CLASS_PATTERN = 73;
  int PARAMETER_ANNOTATION = 74;
  int PARAMETER_JAVA_NAME_LETTER = 75;
  int PARAMETER_NOT = 76;
  int ARG_IDENTIFIER = 77;
  int ARG_PATTERN = 78;
  int ARG_ARRAY_PATTERN = 79;
  int ARG_JAVA_NAME_LETTER = 80;
  int ARGS_END = 81;

  int IN_ARGS = 0;
  int PARAMETERS = 1;
  int FIELD = 2;
  int METHOD = 3;
  int CLASS = 4;
  int DEFAULT = 5;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\",\"",
    "\".\"",
    "\"*\"",
    "\"[]\"",
    "<EAGER_WILDCARD>",
    "<AND>",
    "<OR>",
    "\"!\"",
    "\"execution(\"",
    "\"call(\"",
    "\"set(\"",
    "\"get(\"",
    "\"handler(\"",
    "\"within(\"",
    "\"withincode(\"",
    "\"staticinitialization(\"",
    "\"cflow(\"",
    "\"cflowbelow(\"",
    "\"args(\"",
    "\"target(\"",
    "\"this(\"",
    "\"if(\"",
    "\"hasmethod(\"",
    "\"hasfield(\"",
    "<POINTCUT_REFERENCE_WITH_ARGS>",
    "<POINTCUT_REFERENCE>",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"static\"",
    "\"abstract\"",
    "\"final\"",
    "\"!\"",
    "<CLASS_ATTRIBUTE>",
    "<CLASS_PATTERN>",
    "<CLASS_IDENTIFIER>",
    "<CLASS_JAVA_NAME_LETTER>",
    "\")\"",
    "\"public\"",
    "\"protected\"",
    "\"private\"",
    "\"static\"",
    "\"abstract\"",
    "\"final\"",
    "\"native\"",
    "\"synchronized\"",
    "\"!\"",
    "<METHOD_ANNOTATION>",
    "<METHOD_IDENTIFIER>",
    "<METHOD_CLASS_PATTERN>",
    "<METHOD_ARRAY_CLASS_PATTERN>",
    "\"(\"",
    "\")\"",
    "<METHOD_JAVA_NAME_LETTER>",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"static\"",
    "\"abstract\"",
    "\"final\"",
    "\"transient\"",
    "\"!\"",
    "<FIELD_ANNOTATION>",
    "<FIELD_IDENTIFIER>",
    "<FIELD_CLASS_PATTERN>",
    "<FIELD_ARRAY_CLASS_PATTERN>",
    "<FIELD_JAVA_NAME_LETTER>",
    "\")\"",
    "<PARAMETER_IDENTIFIER>",
    "<PARAMETER_CLASS_PATTERN>",
    "<PARAMETER_ARRAY_CLASS_PATTERN>",
    "<PARAMETER_ANNOTATION>",
    "<PARAMETER_JAVA_NAME_LETTER>",
    "\"!\"",
    "<ARG_IDENTIFIER>",
    "<ARG_PATTERN>",
    "<ARG_ARRAY_PATTERN>",
    "<ARG_JAVA_NAME_LETTER>",
    "\")\"",
    "\"(\"",
    "\")\"",
  };

}
