/* Generated By:JJTree: Do not edit this line. D:/aw/cvs_aw/aspectwerkz3/src/main/org/codehaus/aspectwerkz/expression/ast\ExpressionParserTreeConstants.java */

package org.codehaus.aspectwerkz.expression.ast;

public interface ExpressionParserTreeConstants {
    public int JJTROOT = 0;
    public int JJTEXPRESSION = 1;
    public int JJTVOID = 2;
    public int JJTAND = 3;
    public int JJTOR = 4;
    public int JJTNOT = 5;
    public int JJTPOINTCUTREFERENCE = 6;
    public int JJTEXECUTION = 7;
    public int JJTCALL = 8;
    public int JJTSET = 9;
    public int JJTGET = 10;
    public int JJTHANDLER = 11;
    public int JJTWITHIN = 12;
    public int JJTWITHINCODE = 13;
    public int JJTSTATICINITIALIZATION = 14;
    public int JJTCFLOW = 15;
    public int JJTCFLOWBELOW = 16;
    public int JJTARGS = 17;
    public int JJTHASMETHOD = 18;
    public int JJTHASFIELD = 19;
    public int JJTCLASSPATTERN = 20;
    public int JJTMETHODPATTERN = 21;
    public int JJTCONSTRUCTORPATTERN = 22;
    public int JJTFIELDPATTERN = 23;
    public int JJTPARAMETER = 24;
    public int JJTARGPARAMETER = 25;
    public int JJTATTRIBUTE = 26;
    public int JJTMODIFIER = 27;


    public String[] jjtNodeName = {
        "Root",
        "Expression",
        "void",
        "And",
        "Or",
        "Not",
        "PointcutReference",
        "Execution",
        "Call",
        "Set",
        "Get",
        "Handler",
        "Within",
        "WithinCode",
        "StaticInitialization",
        "Cflow",
        "CflowBelow",
        "Args",
        "HasMethod",
        "HasField",
        "ClassPattern",
        "MethodPattern",
        "ConstructorPattern",
        "FieldPattern",
        "Parameter",
        "ArgParameter",
        "Attribute",
        "Modifier",
    };
}
