/* Generated By:JJTree: Do not edit this line. ExpressionParserTreeConstants.java */

package org.codehaus.aspectwerkz.expression.ast;

public interface ExpressionParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTAND = 2;
  public int JJTOR = 3;
  public int JJTNOT = 4;
  public int JJTPOINTCUTREFERENCE = 5;
  public int JJTEXECUTION = 6;
  public int JJTCALL = 7;
  public int JJTSET = 8;
  public int JJTGET = 9;
  public int JJTHANDLER = 10;
  public int JJTWITHIN = 11;
  public int JJTWITHINCODE = 12;
  public int JJTSTATICINITIALIZATION = 13;
  public int JJTCFLOW = 14;
  public int JJTCFLOWBELOW = 15;
  public int JJTCLASSPATTERN = 16;
  public int JJTMETHODPATTERN = 17;
  public int JJTCONSTRUCTORPATTERN = 18;
  public int JJTFIELDPATTERN = 19;
  public int JJTPARAMETER = 20;
  public int JJTATTRIBUTE = 21;
  public int JJTMODIFIER = 22;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "And",
    "Or",
    "Not",
    "PointcutReference",
    "Execution",
    "Call",
    "Set",
    "Get",
    "Handler",
    "Within",
    "WithinCode",
    "StaticInitialization",
    "Cflow",
    "CflowBelow",
    "ClassPattern",
    "MethodPattern",
    "ConstructorPattern",
    "FieldPattern",
    "Parameter",
    "Attribute",
    "Modifier",
  };
}
