/* Generated By:JJTree: Do not edit this line. ASTBoolean.java */
package org.codehaus.aspectwerkz.annotation.expression.ast;

public class ASTBoolean extends SimpleNode {
    private String m_value;

    public ASTBoolean(int id) {
        super(id);
    }

    public ASTBoolean(ExpressionParser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void setValue(String value) {
        m_value = value;
    }

    public String getValue() {
        return m_value;
    }
}
