/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java */
package org.codehaus.aspectwerkz.annotation.expression.ast;

public class ASTIdentifier extends SimpleNode {
    private String m_value;

    public ASTIdentifier(int id) {
        super(id);
    }

    public ASTIdentifier(AnnotationParser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(AnnotationParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void setValue(String value) {
        m_value = value;
    }

    public String getValue() {
        return m_value;
    }
}
