/* Generated By:JJTree: Do not edit this line. ASTKeyValuePair.java */

package org.codehaus.aspectwerkz.annotation.expression.ast;

public class ASTKeyValuePair extends SimpleNode {
    private String m_key;

    public ASTKeyValuePair(int id) {
        super(id);
    }

    public ASTKeyValuePair(ExpressionParser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
    
    public void setKey(String key) {
        m_key = key;
    }               
    
    public String getKey() {
        return m_key;
    }
}
