/* Generated By:JJTree: Do not edit this line. ASTRoot.java */
package org.codehaus.aspectwerkz.annotation.expression.ast;

public class ASTRoot extends SimpleNode {
    public ASTRoot(int id) {
        super(id);
    }

    public ASTRoot(AnnotationParser p, int id) {
        super(p, id);
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(AnnotationParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
