/* Generated By:JJTree: Do not edit this line. ASTString.java */
package org.codehaus.aspectwerkz.annotation.expression.ast;

public class ASTString extends SimpleNode {
    private String m_value;

    public ASTString(int id) {
        super(id);
    }

    public ASTString(ExpressionParser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public void setValue(String value) {
        m_value = value;
    }

    public String getValue() {
        return m_value;
    }
}
