/* Generated By:JJTree: Do not edit this line. ExpressionParserVisitor.java */

package org.codehaus.aspectwerkz.annotation.expression.ast;

public interface ExpressionParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTRoot node, Object data);
  public Object visit(ASTAnnotation node, Object data);
  public Object visit(ASTKeyValuePair node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTBoolean node, Object data);
  public Object visit(ASTChar node, Object data);
  public Object visit(ASTString node, Object data);
  public Object visit(ASTArray node, Object data);
}
