/* Generated By:JJTree: Do not edit this line. ExpressionParserTreeConstants.java */

package org.codehaus.aspectwerkz.annotation.expression.ast;

public interface ExpressionParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTANNOTATION = 1;
  public int JJTKEYVALUEPAIR = 2;
  public int JJTVOID = 3;
  public int JJTIDENTIFIER = 4;
  public int JJTBOOLEAN = 5;
  public int JJTCHAR = 6;
  public int JJTSTRING = 7;
  public int JJTARRAY = 8;


  public String[] jjtNodeName = {
    "Root",
    "Annotation",
    "KeyValuePair",
    "void",
    "Identifier",
    "Boolean",
    "Char",
    "String",
    "Array",
  };
}
